// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx3cRnat95dpty9qSR8pWWWnxi6VhL0TI',
    appId: '1:862072193394:web:38a0c61c9c200b8afc1deb',
    messagingSenderId: '862072193394',
    projectId: 'fruit-hub-5d65c',
    authDomain: 'fruit-hub-5d65c.firebaseapp.com',
    storageBucket: 'fruit-hub-5d65c.firebasestorage.app',
    measurementId: 'G-KLPWHMQEKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtLgFqHMYb9_B6cSWhUMzx_hHlS6I0nos',
    appId: '1:862072193394:android:70f9bc88f0edd343fc1deb',
    messagingSenderId: '862072193394',
    projectId: 'fruit-hub-5d65c',
    storageBucket: 'fruit-hub-5d65c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsaRdMkr86NUPgnS-5Ef83PIyAIc7WLiQ',
    appId: '1:862072193394:ios:d308d841b92cbc2afc1deb',
    messagingSenderId: '862072193394',
    projectId: 'fruit-hub-5d65c',
    storageBucket: 'fruit-hub-5d65c.firebasestorage.app',
    androidClientId: '862072193394-1dc8rur0q6i73p5emucndpl3gdh423fs.apps.googleusercontent.com',
    iosClientId: '862072193394-tckd8355ifo3gr3bvqp1dd3jnecg3cuc.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsaRdMkr86NUPgnS-5Ef83PIyAIc7WLiQ',
    appId: '1:862072193394:ios:d308d841b92cbc2afc1deb',
    messagingSenderId: '862072193394',
    projectId: 'fruit-hub-5d65c',
    storageBucket: 'fruit-hub-5d65c.firebasestorage.app',
    androidClientId: '862072193394-1dc8rur0q6i73p5emucndpl3gdh423fs.apps.googleusercontent.com',
    iosClientId: '862072193394-tckd8355ifo3gr3bvqp1dd3jnecg3cuc.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx3cRnat95dpty9qSR8pWWWnxi6VhL0TI',
    appId: '1:862072193394:web:c5939cbceeeb5273fc1deb',
    messagingSenderId: '862072193394',
    projectId: 'fruit-hub-5d65c',
    authDomain: 'fruit-hub-5d65c.firebaseapp.com',
    storageBucket: 'fruit-hub-5d65c.firebasestorage.app',
    measurementId: 'G-978WB2FG34',
  );
}
